[build]
  command = "hugo --gc --minify"
  publish = "public"
[build.environment]
  HUGO_VERSION = "0.134.3"
  HUGO_ENV = "production"
[functions]
  directory = "netlify/functions"
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
[[redirects]]
  from = "/auth"
  to = "/.netlify/functions/auth"
  status = 200
  force = true
